- name: Install apache httpd  (state=present is optional)
  ansible.builtin.apt:
    name: "{{ package }}"
    state: present
    update_cache: yes

- name: Start apache
  ansible.builtin.service:
    name: "{{ package }}"
    state: started 
    enabled: yes   
# tasks file for Apache
