- name: Install apache httpd
  ansible.builtin.apt:
    name: "{{ apache_package }}"
    state: present
    update_cache: yes

- name: Start apache
  ansible.builtin.service:
    name: "{{ apache_package }}"
    state: started
    enabled: yes
# tasks file for Apache
