- name: Install mysql  (state=present is optional)
  ansible.builtin.apt:
    name: mysql-server
    state: present

- name: Install PyMySQL  (state=present is optional)
  ansible.builtin.apt:
    name: python3-pymysql
    state: present    

- name: Start mysql
  ansible.builtin.service:
    name: mysql
    state: started 
    enabled: yes   

- name: Create Database
  community.mysql.mysql_db:
    name: "{{ mysql_database }}"
    state: present
    login_unix_socket: /run/mysqld/mysqld.sock

- name: Create MySQL User
  community.mysql.mysql_user:
    name: "{{ mysql_user }}"
    password: "{{ mysql_password }}"
    priv: '*.*:ALL'
    state: present
    login_unix_socket: /run/mysqld/mysqld.sock
# tasks file for Mysql
