- hosts: all
  become: yes
  tasks:
  - name: Install unzip
    ansible.builtin.apt:
      name: unzip
      state: present
      update_cache: yes

  - name: Install mariadb-client
    ansible.builtin.apt:
      name: mariadb-client
      state: present    
      update_cache: yes

  - name: Install mariadb-server
    ansible.builtin.apt:
      name: mariadb-server
      state: present    
      update_cache: yes    

  - name: Start service mariadb-client, if not started
    ansible.builtin.service:
      name: mariadb
      state: started
      enabled: yes     