- hosts: all
  become: yes
  tasks:
  - name: Update APT repository cache
    ansible.builtin.apt:
      update_cache: yes

  - name: Install unzip
    ansible.builtin.apt:
      name: unzip
      state: present

  - name: Install mariadb-client
    ansible.builtin.apt:
      name: mariadb-client
      state: present    
     

  - name: Install mariadb-server
    ansible.builtin.apt:
      name: mariadb-server
      state: present    
       

  - name: Start mariadb service
    ansible.builtin.service:
      name: mariadb
      state: started
      enabled: yes     