- hosts: all
  become: yes
  tasks:
    - name: create users
      ansible.builtin.user:
        name: "{{ item }}"
        state: present
      loop:
        - slava
        - tim
        - ann

    - name: Create groups
      ansible.builtin.group:
        name: "{{ item }}"
        state: present
      loop:
        - devops
        - qa 

    - name: Add slava to devops group
      ansible.builtin.user:
        name: slava
        groups: devops
        append: yes

    - name: Add tim to qa group
      ansible.builtin.user:   
        name: tim
        groups: qa
        append: yes

    - name: Add ann to qa group
      ansible.builtin.user:
        name: ann
        groups: qa
        append: yes      